alias add='git add'
alias addall='git add -A'
alias addi='git add -i'
alias amend='git commit --amend'
alias branch='git branch'
alias chpick='git cherry-pick'
alias clone='git clone'
alias cls='clear'
alias co='git checkout'
alias emit='git commit -e'
alias fetch='git fetch'
alias merge='git merge'
alias mit='git commit -m'
alias nomerged='git branch --no-merged'
alias pull='git pull'
alias push='git push'
alias rebase='git rebase'
alias remote='git remote --verbose'
alias remoteadd='git remote add origin'
alias remoteurl='git remote set-url origin'
alias stash='git stash'
alias stashdiff='git stash show -p'
alias stat='git status'
alias v='ls -alh'
alias lghead='git log origin..HEAD'
alias lgline='git log --oneline'
alias lgshort='git log --format=short'
alias lgmine="git log --graph --decorate --format='%C(yellow)%h %C(cyan)%ad%C(auto)%d%n%n    %C(green italic)%an %C(cyan)(%ar) %C(reset)%s%n' --date=format:'%m-%d-%y %H:%M [%a]'"

alias cgit='cd /c/git' 
alias discardall='git status | grep modified: | cut -d'\'' '\'' -f 2- | awk '\''{gsub(/^ +| +$/,"")} {print "\""$0"\""}'\'' | xargs git checkout -- ' 
